# Generated by Django 5.0.6 on 2024-07-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'TODO Item',
            },
        ),
    ]
